### ISSUE TITLE
Using Textual Entailment to retrieve evidence

### ISSUE THREAD

**Issue by anikethjr** [DeFacto/DeFactoNLP#2]
Code a function `textual_entailment_evidence_retriever(claim, potential_evidence_sentences)` where `claim` is the statement whose veracity we have to determine and `potential_evidence_sentences` is a list of sentences which could possibly support or refute the claim or provide no relevant information. The function should return a dictionary called `results` which will have three fields:

1. `claim`: the original claim
2. `label`: overall classification for the claim - SUPPORTS, REFUTES or NOT ENOUGH INFO
3. `evidence`: if the `label` is SUPPORTS or REFUTES, then it is the list of sentences which either support or refute the claim else it is an empty list

**Comment by GilRocha** [comment]
Function `textual_entailment_evidence_retriever(claim, potential_evidence_sentences)` can be found at "./rte/rte.py".

TODOs:

- [ ] Run RTE model on full SNLI corpus (due to lack of computational resources and time, I was unable to run the code on the full SNLI corpus)
- [x] Improve function `determinePredictedLabel(preds)` -> current implementation: returns the label ymax, where ymax is the label predicted more times given the evidence (this was created by a Random Forest)

**Comment by diegoesteves** [comment]
@pedrojlazevedo shall we close this? v1.0 should cover it.

**Comment by pedrojlazevedo** [comment]
@diegoesteves, @GilRocha is the one that will know if RTE model was trained on the full SNLI corpus. Shall we close?
